### PR TITLE
Use CARGO_ENCODED_RUSTFLAGS when it is set

### PR DESCRIPTION
**Pull request by cuviper**

### CODE REVIEW

**Review by ColinFinck — APPROVED** [review]
I can confirm that this PR works equally well for me as my #38
Would love to see it appear in 1.0.x and 0.1.x releases as soon as possible :)

**Comment by ColinFinck** [comment]
@cuviper Can this be merged and released?

**Comment by frankplus** [comment]
I would also like this to be merged and released.
Thanks :)

**Comment by cuviper** [comment]
Published as 1.1.0, as well as a re-export as 0.1.8.

**Pull request merged**
